### ISSUE TITLE
DotNet 4.6 Compatibility

### ISSUE THREAD

**Issue by sganz** [JakeBayer/FuzzySharp#2]
Found you Nuget and looks great for my applicaiton, but can't run it with a DotNet 4.6+ project. Got this error from the package installer -

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'FuzzySharp 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Any way to make it compatible?

Thanks

Sandy

**Comment by JakeBayer** [comment]
Hey,

Thanks for bringing this to my attention. I've never made a nuget package multi-version compatible before, but I think I was able to figure it out. I have pushed a 1.0.1 version of this package that should be compatible with both .net45 and .net46 frameworks. Look for it to be validated/available on the nuget library in the next hour or so, and let me know if you have any further problems

**Comment by sganz** [comment]
Jake -

Just got in and going to give it a test this morning. Thank you very much for the super quick fix! I had loaded the BoomTown.FuzzySharp version but liked your code better. 

Hopefully will be all good!

Thanks again
Sandy

**Comment by sganz** [comment]
Got it working, thanks again for the super quick fix!
Sandy

**Comment by JakeBayer** [comment]
No problem, glad I could be of help
Jake

**Comment by hanivaidehi** [comment]
Hi Jake

Can I have a link for 1.0.1 version of this package that is compatible with both .net45 and .net46? Thank you
