### ISSUE TITLE
FuzzySharp for non-Latin languages

### ISSUE THREAD

**Issue by duffyphil** [JakeBayer/FuzzySharp#37]
We would like to use FuzzySharp for string comparison in some non-Latin languages, including Greek and Russian.
Please can you confirm the best way to use FuzzySharp for this purpose is the Extract methods in the Process class, using the parameter (s) => s
Many thanks

**Comment by JakeBayer** [comment]
That is certainly one way to do it. However, it will obviously depend on your use case. For example, you might want to ignore capitalization, so something like `(s) => s.ToLower()` might also be appropriate. The lambda you provide here is simply a pre-processing function that should be run on all strings before the comparison. The lambda `(s) => s` will perform no pre-processing to the strings, as it simply just returns the string itself. If that is what fits your use case, then by all means go for it.

Let me know if you have any further questions.
