### ISSUE TITLE
Release 1.0.2 on NuGet

### ISSUE THREAD

**Issue by domyd** [JakeBayer/FuzzySharp#4]
I noticed the latest commit bumped the version to 1.0.2 and added compatibility with netstandard & co, however the latest version on NuGet is still 1.0.1. 

Could you push 1.0.2 to NuGet? In the meantime I've compiled and packaged 1.0.2 myself and checked it into my project, but having it come from NuGet directly would be much nicer 🙂

**Comment by JakeBayer** [comment]
Just pushed the latest to NuGet and the package is currently being validated. Newest version should be available in a day or so.

Thanks for catching this!
