### ISSUE TITLE
Index of out range in TokenInitialismRatio

### ISSUE THREAD

**Issue by Gawaboumga** [JakeBayer/FuzzySharp#5]
Hello, I was using your library without any issue until I fell off on this case:

I got an exception when using "TokenInitialismRatio" with those two words: "lusiki plaza share block  " (with a space) and "jmft".

Here is the StackTrace:
Exception thrown: 'System.IndexOutOfRangeException' in FuzzySharp.dll
System.Transactions Critical: 0 : Blablabal
<Message>Index was outside the bounds of the array.</Message><StackTrace>   at FuzzySharp.SimilarityRatio.Scorer.StrategySensitive.TokenInitialismScorerBase.&amp;lt;&amp;gt;c.&amp;lt;Score&amp;gt;b__0_0(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at FuzzySharp.SimilarityRatio.Scorer.StrategySensitive.TokenInitialismScorerBase.Score(String input1, String input2)
Then my code  =)

Yours sincerely.

**Comment by JakeBayer** [comment]
Thanks for bringing this bug to my attention! I will get a fix in and push the new version ASAP.

**Comment by JakeBayer** [comment]
This particular issue has been fixed and should be out with version 1.0.4 of FuzzySharp when the package is validated with nuget. This process usually takes about an hour.

Thanks for using FuzzySharp!
